config/routes.rb
Rails.application.routes.draw do
  
  root to: "main#index"
  get "about", to: "about#index"
  # With Rails, the same URL can handle different kind of requests
  # Rails calls them VERB(get, post, patch, put, delete, etc)
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  
  delete "logout", to: "sessions#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# email:string
# password_digest:string

# We won't be interacting with password_digest whenever we create a user. We'll instead interact virtual attributes that comes with has_secured_password. What it'll do for us is:
  # 1. has_secure_password will check if password & password confirmation matches each other.
  # 2. Once matched, it'll run through bcrypt to create a digest 
  # 3. Assign that digest to password_digest for us
# password:string virtual
# password_confirmation:string virtual

class User < ApplicationRecord
  # This is a rails feature for password
  has_secure_password

  # Rails feature to ensure an email is present before making an entry into the database
  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address"}
  # The other way of validating is through migration table.
    # t.string: email, null: false
    # This will ensure that email needs to be present in order to create a user/data
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    # pt 15 for more info
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    # flash[:notice] = "Successfully logged in"
    # flash[:alert] = "Invalid email or password"
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    # In ruby if we don't use instance variable(@), the variable will be wiped out and won't be shown in views. Refer to part 13 for more info.
    @user = User.new  
  end

  def create
    # Part 14 explains params really well
    # render plain: params -> This prints out the whole object with their params
    # render plain: params[:user] -> This prints out user object with its params 
    # To create a new user in our database, we'll use params[:user] and insert its data into our model
    # This should be done under private section below to make it secure
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id # This will look into main_controller.rb for the user
      redirect_to root_path, notice: "Successfully created account"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password]) # authenticate method comes from has_secure_password
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in successfully"
    else
      flash[:alert] = "Invalid email or password"
      render :new
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <!-- Bootstrap JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <div class="container">
        <%= render partial: "shared/navbar" %>
        <%= render partial: "shared/flash"%>
        <%= yield %>
      <div>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1>Welcome to Scheduled Tweets</h1>

</div>
<% if @user %>
  Logged in as: <%= @user.email %>

  <%= button_to "Logout", logout_path, method: :delete %>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>